services:
  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379