"""new table

Revision ID: 01360609f6ab
Revises: c37c6df505a5
Create Date: 2025-08-26 03:16:13.946472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01360609f6ab'
down_revision: Union[str, Sequence[str], None] = 'c37c6df505a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptos_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crypto_id', sa.Integer(), nullable=True),
    sa.Column('thumb', sa.String(), nullable=True),
    sa.Column('small', sa.String(), nullable=True),
    sa.Column('large', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cryptos_images_id'), 'cryptos_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cryptos_images_id'), table_name='cryptos_images')
    op.drop_table('cryptos_images')
    # ### end Alembic commands ###
