"""change tables

Revision ID: 1b97c74d5382
Revises: bb416cad5694
Create Date: 2025-08-26 04:09:15.712698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b97c74d5382'
down_revision: Union[str, Sequence[str], None] = 'bb416cad5694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptos', sa.Column('symbol', sa.String(), nullable=True))
    op.add_column('cryptos', sa.Column('market_cap_rank', sa.Integer(), nullable=True))
    op.add_column('cryptos', sa.Column('genesis_date', sa.Date(), nullable=True))
    op.add_column('cryptos', sa.Column('hashing_algorithm', sa.String(), nullable=True))
    op.add_column('cryptos', sa.Column('max_supply', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('prices', sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('prices', sa.Column('volume_24h', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('prices', sa.Column('price_change_24h', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('prices', sa.Column('price_change_percentage_24h', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('prices', sa.Column('ath', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('prices', sa.Column('atl', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('prices', sa.Column('circulating_supply', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('prices', sa.Column('total_supply', sa.Numeric(precision=20, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'total_supply')
    op.drop_column('prices', 'circulating_supply')
    op.drop_column('prices', 'atl')
    op.drop_column('prices', 'ath')
    op.drop_column('prices', 'price_change_percentage_24h')
    op.drop_column('prices', 'price_change_24h')
    op.drop_column('prices', 'volume_24h')
    op.drop_column('prices', 'market_cap')
    op.drop_column('cryptos', 'max_supply')
    op.drop_column('cryptos', 'hashing_algorithm')
    op.drop_column('cryptos', 'genesis_date')
    op.drop_column('cryptos', 'market_cap_rank')
    op.drop_column('cryptos', 'symbol')
    # ### end Alembic commands ###
