"""change tables

Revision ID: 64e17f5bfcf1
Revises: 66e9de332430
Create Date: 2025-08-26 03:27:24.095760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e17f5bfcf1'
down_revision: Union[str, Sequence[str], None] = '66e9de332430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cryptos_images_id'), table_name='cryptos_images')
    op.drop_table('cryptos_images')
    op.add_column('cryptos', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cryptos', 'image')
    op.create_table('cryptos_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('crypto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thumb', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('small', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('large', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptos.id'], name=op.f('cryptos_images_crypto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cryptos_images_pkey'))
    )
    op.create_index(op.f('ix_cryptos_images_id'), 'cryptos_images', ['id'], unique=False)
    # ### end Alembic commands ###
