"""change tables

Revision ID: 7f6dd6ff2b8a
Revises: 1b97c74d5382
Create Date: 2025-08-26 04:11:08.039521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6dd6ff2b8a'
down_revision: Union[str, Sequence[str], None] = '1b97c74d5382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('ath_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('prices', sa.Column('atl_date', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'atl_date')
    op.drop_column('prices', 'ath_date')
    # ### end Alembic commands ###
