"""change tables

Revision ID: b9d3b494add9
Revises: 7f6dd6ff2b8a
Create Date: 2025-08-26 04:47:33.003963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d3b494add9'
down_revision: Union[str, Sequence[str], None] = '7f6dd6ff2b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('market_cap_change_24h', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('prices', sa.Column('market_cap_change_percentage_24h', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_column('prices', 'volume_24h')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('volume_24h', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True))
    op.drop_column('prices', 'market_cap_change_percentage_24h')
    op.drop_column('prices', 'market_cap_change_24h')
    # ### end Alembic commands ###
