"""update crypto id

Revision ID: bb416cad5694
Revises: 92218931d620
Create Date: 2025-08-26 03:35:04.521332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb416cad5694'
down_revision: Union[str, Sequence[str], None] = '92218931d620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'prices', 'cryptos', ['crypto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prices', type_='foreignkey')
    # ### end Alembic commands ###
